# https://taskfile.dev

version: "3"

vars:
  GREETING: Boltzmann distribution

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    # deps: [clean]
    cmds:
      - python ./main.py --log=DEBUG

  run:gpu:
    # deps: [clean]
    cmds:
      - python ./main-gpu.py --log=DEBUG

  lint:
    cmds:
      - pylint --rcfile=../../.pylintrc   .

  test:
    cmds:
      - pytest

  test-default:
    cmds:
      - pytest -v -s test_Particle.py::test_default

  clean:
    cmds:
      - rm -rf *.gif
