# https://taskfile.dev

version: "3"

vars:
  GREETING: Pytorch tutorial

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  billiards:
    deps: [clean]
    cmds:
      - python ./main.py

  tests:
    cmds:
      - pytest

  clean:
    cmds:
      - rm -rf *.gif
